# Generated by Django 4.2.5 on 2023-09-21 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('email', models.CharField(max_length=50, unique=True, verbose_name='email')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('surname', models.CharField(max_length=150, verbose_name='surname')),
                ('patronymic', models.CharField(max_length=150, verbose_name='patronymic')),
                ('comments', models.TextField(verbose_name='comments')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('theme', models.CharField(max_length=50, verbose_name='theme')),
                ('content', models.TextField(verbose_name='content')),
            ],
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('mailing_time', models.DateTimeField(verbose_name='mailing time')),
                ('frequency', models.IntegerField(choices=[(0, 'Once a day'), (1, 'Once a week'), (2, 'Once a month')], default=1, verbose_name='mailing frequency')),
                ('mailing_status', models.IntegerField(choices=[(0, 'Created'), (1, 'Running'), (2, 'Finished')], default=0)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailer.message', verbose_name='message')),
                ('recipients', models.ManyToManyField(to='mailer.client', verbose_name='recipients')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='timestamp')),
                ('status', models.BooleanField(choices=[(1, 'Successful'), (0, 'Unsuccessful')], verbose_name='status')),
                ('response', models.TextField(blank=True, verbose_name='response')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailer.mailing', verbose_name='mailing')),
            ],
        ),
    ]
