# Generated by Django 4.2.5 on 2023-10-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='changed_at',
            field=models.DateTimeField(auto_now=True, verbose_name='change date'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='changed_at',
            field=models.DateTimeField(auto_now=True, verbose_name='change date'),
        ),
        migrations.AddField(
            model_name='message',
            name='changed_at',
            field=models.DateTimeField(auto_now=True, verbose_name='change date'),
        ),
    ]
