# Generated by Django 4.2.5 on 2023-10-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0002_client_changed_at_mailing_changed_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailing',
            old_name='mailing_time',
            new_name='end_time',
        ),
        migrations.AddField(
            model_name='mailing',
            name='start_time',
            field=models.DateTimeField(verbose_name='mailing time'),
            preserve_default=False,
        ),
    ]
