# Generated by Django 4.2.5 on 2023-10-13 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0004_alter_mailing_end_time_alter_mailing_start_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='log',
            options={'verbose_name': 'Log', 'verbose_name_plural': 'Logs'},
        ),
        migrations.AlterModelOptions(
            name='mailing',
            options={'verbose_name': 'Mailing', 'verbose_name_plural': 'Mailings'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
    ]
