# Generated by Django 4.2.5 on 2023-10-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('changed_at', models.DateTimeField(auto_now=True, verbose_name='change date')),
                ('header', models.CharField(max_length=150, unique=True, verbose_name='header')),
                ('content', models.TextField(verbose_name='content')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='views count')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_images', verbose_name='preview')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
